CREATE TABLE poi 
(
	poi_id INTEGER PRIMARY KEY AUTO_INCREMENT,
    map_id INTEGER NOT NULL,
    x INTEGER NOT NULL,
    y INTEGER NOT NULL,
    img_src VARCHAR(45) NOT NULL,
    added TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (map_id) REFERENCES map (map_id) ON DELETE CASCADE ON UPDATE CASCADE
)