DELETE FROM map where map_id > 0;
ALTER TABLE map AUTO_INCREMENT=1;
ALTER TABLE wifi AUTO_INCREMENT=1;
ALTER TABLE room AUTO_INCREMENT=1;
ALTER TABLE position AUTO_INCREMENT=1;
ALTER TABLE poi AUTO_INCREMENT=1;